# Generated by Django 4.2.13 on 2024-06-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshowimage',
            name='has_btn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slideshowimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slideshowimage',
            name='link',
            field=models.CharField(default='#', max_length=300),
        ),
    ]
