# Generated by Django 4.2.13 on 2024-06-20 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_galleryimage_patientimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=400)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('link', models.CharField(default='#', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('has_btn', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='course_images/')),
            ],
        ),
    ]
