# Generated by Django 4.2.13 on 2024-06-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_mymodel_remove_course_image_courseimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshowimage',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
    ]
