# Generated by Django 4.2.13 on 2024-06-23 17:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_slideshowimage_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideShowImageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('text', models.CharField(max_length=200)),
                ('link', models.CharField(default='#', max_length=300)),
                ('has_btn', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='slideshow_images/')),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'SlideShowImage Translation',
                'db_table': 'website_slideshowimage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='patientimage',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='slideshowimage',
            options={'ordering': ('-created',), 'verbose_name': 'SlideShowImage', 'verbose_name_plural': 'SlideShowImages'},
        ),
        migrations.RemoveField(
            model_name='slideshowimage',
            name='has_btn',
        ),
        migrations.RemoveField(
            model_name='slideshowimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='slideshowimage',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='slideshowimage',
            name='link',
        ),
        migrations.RemoveField(
            model_name='slideshowimage',
            name='text',
        ),
        migrations.RemoveField(
            model_name='slideshowimage',
            name='title',
        ),
        migrations.AddField(
            model_name='course',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slideshowimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slideshowimagetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='website.slideshowimage'),
        ),
        migrations.AlterUniqueTogether(
            name='slideshowimagetranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
