# Generated by Django 4.2.13 on 2024-06-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_slideshowimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetranslation',
            name='text',
            field=models.CharField(blank=True, default=' ', max_length=400, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='text',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='text',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='slideshowimagetranslation',
            name='text',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='slideshowimagetranslation',
            name='title',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='title'),
        ),
    ]
